name:                lyhgg
version:             0.1.0.0
github:              "nabinno/dojo/blob/master/lyhgg"
license:             MIT
author:              "Nab Inno"
maintainer:          "nab@blahfe.com"
copyright:           "2020 Nab Inno"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nabinno/dojo/master/blob/lyhgg#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lyhgg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lyhgg

tests:
  lyhgg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lyhgg
